[package]
name = "pick3"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.30.1", directory="noir-projects/aztec-nr/aztec" }